#define TAPPING_TERM 250
#define TAPPING_TERM_PER_KEY
#define PLOOPY_DPI_OPTIONS { 400, 1600 }
#define PLOOPY_DPI_DEFAULT 1
#define PLOOPY_DRAGSCROLL_MOMENTARY
#define PLOOPY_DRAGSCROLL_INVERT
#define PLOOPY_DRAGSCROLL_FIXED
#define PLOOPY_DRAGSCROLL_DPI 100
#define OPT_DEBOUNCE 0